IF EMO_ACTIVE=1 THEN
	ErrCode=10
	PRINT "EMO Active"
	goto endHome
ENDIF

PRINT "Homing X2Y2Z2"
WDOG=1
GX2Y2Z2Status=3
ErrCode=0


'GX2Y2Z2
BASE(GX2Axis,GY2Axis,GZ2Axis)
ACCEL=GXYHOME_SPEEDPROF(3),XY2HOME_SPEEDPROF(3),GZHOME_SPEEDPROF(3)
DECEL=GXYHOME_SPEEDPROF(2),XY2HOME_SPEEDPROF(2),GZHOME_SPEEDPROF(2)
SPEED=GXYHOME_SPEEDPROF(0),XY2HOME_SPEEDPROF(0),GZHOME_SPEEDPROF(0)
CREEP=GXYHOME_SPEEDPROF(0),XY2HOME_SPEEDPROF(0),GZHOME_SPEEDPROF(0)


FOR i=0 to 2
	DATUM(0)AXIS(i)
NEXT

'GZ2Home
DELAY(500)
AXIS_ENABLE(GZ2Axis)=1
DELAY(50)
IF AXISSTATUS(GZ2Axis)<> 0 AND AXISSTATUS(GZ2Axis)<> 16  AND AXISSTATUS(GZ2Axis)<> 32   THEN
	AXIS_ENABLE(GZ2Axis) = 0
	GX2Y2Z2Status = 2
	ErrCode = 2200
	goto endHome
ENDIF		
DELAY(50)
DATUM(4)AXIS(GZ2Axis)
MOVE(-2)AXIS(GZ2Axis)
WAIT UNTIL IDLE(GZ2Axis)
DATUM(0)AXIS(GZ2Axis)
BASE(GZ2Axis)
DPOS=0
MPOS=0

'GX2Y2Home
FOR i=0 to 1
	DATUM(0)AXIS(i)
NEXT
DELAY(500)
AXIS_ENABLE(GX2Axis)=1
AXIS_ENABLE(GY2Axis)=1
IF AXISSTATUS(GX2Axis)<> 0 AND AXISSTATUS(GX2Axis)<> 16  AND AXISSTATUS(GX2Axis)<> 32  THEN
	AXIS_ENABLE(GX2Axis) = 0
	GX2Y2Z2Status = 2
	ErrCode = 2000
	goto endHome
ENDIF
IF AXISSTATUS(GY2Axis)<> 0 AND AXISSTATUS(GY2Axis)<> 16  AND AXISSTATUS(GY2Axis)<> 32  THEN
	AXIS_ENABLE(GY2Axis) = 0
	GX2Y2Z2Status = 2
	ErrCode = 2100
	goto endHome
ENDIF
DATUM(4)AXIS(GX2Axis)
MOVE(2)AXIS(GX2Axis)
DELAY(1000)
DATUM(3)AXIS(GY2Axis)
MOVE(-2)AXIS(GY2Axis)
WAIT UNTIL IDLE(GX2Axis) AND IDLE(GY2Axis)
BASE(GX2Axis,GY2Axis)
DPOS=0,0
MPOS=0,0

PRINT "Home X2Y2Z2 Succes"
GX2Y2Z2Status = 1
GOTO endHome

endHome:
PRINT "HOME X2Y2Z2 Error Code" +ErrCode
PRINT "Status" +GX2Y2Z2Status
END