IF EMO_ACTIVE=1 THEN
	ErrCode=10
	PRINT "EMO Active"
	goto endHome
ENDIF

PRINT "Homing XYZ"
WDOG=1
GXYZStatus=3
ErrCode=0

'GXYZ
BASE(GXAxis,GYAxis,GZAxis)
ACCEL=GXYHOME_SPEEDPROF(3),GXYHOME_SPEEDPROF(3),GZHOME_SPEEDPROF(3)
DECEL=GXYHOME_SPEEDPROF(2),GXYHOME_SPEEDPROF(2),GZHOME_SPEEDPROF(2)
SPEED=GXYHOME_SPEEDPROF(0),GXYHOME_SPEEDPROF(0),GZHOME_SPEEDPROF(0)
CREEP=GXYHOME_SPEEDPROF(0),GXYHOME_SPEEDPROF(0),GZHOME_SPEEDPROF(0)

for i=6 to 8
	DRIVE_CLEAR(0)AXIS(i)
NEXT

DELAY(200)

FOR i=6 to 8
	DATUM(0)AXIS(i)
NEXT

'GZHome
DELAY(500)
AXIS_ENABLE(GZAxis)=1
DELAY(50)
	TIMER_START(0,10000)
	wait UNTIL TIMER_IFEND(0) = 1 or READ_BIT2(7,DRIVE_STATUS(GZAxis))<> 1 OR GPhaseFindDone <> 0  
	
	TIMER_STOP(0)
	IF READ_BIT2(7,DRIVE_STATUS(GZAxis))<> 0 and GPhaseFindDone = 0  THEN
			AXIS_ENABLE(GZAxis) = 0
			GXYZStatus = 2
			ErrCode = 2806
		GOTO endHome
	ENDIF	
	IF AXISSTATUS(GZAxis)<> 0 AND AXISSTATUS(GZAxis)<> 16  AND AXISSTATUS(GZAxis)<> 32   THEN
		AXIS_ENABLE(GZAxis) = 0
		GXYZStatus = 2
		ErrCode = 2800
		goto endHome
	ENDIF		

DELAY(50)
DATUM(3)AXIS(GZAxis)
WAIT UNTIL IDLE(GZAxis)
DELAY(1000)
BASE(GZAxis)
DPOS=0
MPOS=0

'GXYHome
for i=6 to 7
	DRIVE_CLEAR(0)AXIS(i)
NEXT
DELAY(200)

FOR i=6 to 7
	DATUM(0)AXIS(i)
NEXT

DELAY(500)
AXIS_ENABLE(GYAxis)=1
AXIS_ENABLE(GXAxis)=1
TIMER_START(0,10000)
WAIT UNTIL TIMER_IFEND(0)=1 OR READ_BIT2(7,DRIVE_STATUS(GYAxis))<>1 AND READ_BIT2(7,DRIVE_STATUS(GXAxis))<>1 OR GPhaseFindDone<>0
TIMER_STOP(0)
IF READ_BIT2(7,DRIVE_STATUS(GYAxis))<>0 and GPhaseFindDone=0 THEN
	AXIS_ENABLE(GYAxis)=0
	GXYZStatus=2
	ErrCode=2706
	goto endHome
ELSEIF READ_BIT2(7,DRIVE_STATUS(GYAxis))<>0 and IN(FWD_IN(GYAxis))<>0 THEN
	AXIS_ENABLE(GYAxis)=0
	GXYZStatus=2
	ErrCode=2707
	goto endHome
ENDIF
IF AXISSTATUS(GYAxis)<> 0 AND AXISSTATUS(GYAxis)<> 16  AND AXISSTATUS(GYAxis)<> 32  THEN
	AXIS_ENABLE(GYAxis) = 0
	GXYZStatus = 2
	ErrCode = 2700
	goto endHome
ENDIF

IF READ_BIT2(7,DRIVE_STATUS(GXAxis))<>0 and GPhaseFindDone=0 THEN
	AXIS_ENABLE(GXAxis)=0
	GXYZStatus=2
	ErrCode=2606
	goto endHome
ELSEIF READ_BIT2(7,DRIVE_STATUS(GXAxis))<>0 and IN(REV_IN(GXAxis))<>0 THEN
	AXIS_ENABLE(GXAxis)=0
	GXYZStatus=2
	ErrCode=2607
	goto endHome
ENDIF
IF AXISSTATUS(GXAxis)<> 0 AND AXISSTATUS(GXAxis)<> 16  AND AXISSTATUS(GXAxis)<> 32  THEN
	AXIS_ENABLE(GXAxis) = 0
	GXYZStatus = 2
	ErrCode = 2600 
	goto endHome
ENDIF

'DATUM(4)AXIS(GXAxis)
'MOVE(5)AXIS(GXAxis)
'DELAY(1000)
'DATUM(3)AXIS(GYAxis)
'MOVE(-5)AXIS(GYAxis)
'WAIT UNTIL IDLE(GXAxis) AND IDLE(GYAxis)
'DELAY(1000)
'BASE(GXAxis,GYAxis)
'DPOS=0,0
'MPOS=0,0
DATUM(21, HOMEMODE(GXAxis)) AXIS(GXAxis)
DELAY(1000)
DATUM(21, HOMEMODE(GYAxis)) AXIS (GYAxis)
WAIT UNTIL IDLE(GXAxis) AND IDLE(GYAxis)
PRINT AXISSTATUS(GXAxis)
PRINT AXISSTATUS(GYAxis)
PRINT "Home XYZ Succes"
GXYZStatus = 1
GOTO endHome

endHome:
PRINT "HOME XYZ Error Code" +ErrCode
PRINT "Status" +GXYZStatus
END
