'||| Burn Run Program : Gantry Top  ||

DIM POSX(6)
POSX(0, 0, 50, 150, 250, 300, 350)
DIM POSY(6)
POSY(0, 0, -10, -100, -250, -350, -500) 
DIM POSZ(6)
POSZ(0, 0, -5, -10, -15, -20, -25) 

BASE (GXAxis,GYAxis,GZAxis)
SPEED = 2000, 2000, 500
ACCEL =  18000, 18000, 2000
DECEL = 18000, 18000, 2000
FASTDEC = 20000, 20000, 20000

AXIS_ENABLE(GZAxis) = 1
AXIS_ENABLE(GYAxis) = 1
DELAY(100)
AXIS_ENABLE(GXAxis) = 1

DELAY(200)

	WHILE 1
			'Motion 1
			MOVEABS(POSX(5)) AXIS(GXAxis)
			WAIT UNTIL IDLE(GXAxis) 
			MOVEABS(POSX(3)) AXIS(GXAxis)
			WAIT UNTIL IDLE(GXAxis) 
			MOVEABS(POSY(5)) AXIS(GYAxis)
			WAIT UNTIL IDLE(GYAxis)
			MOVEABS(POSZ(5)) AXIS(GZAxis)
			WAIT UNTIL IDLE(GZAxis) 
			MOVEABS(POSZ(0)) AXIS(GZAxis)
			WAIT UNTIL IDLE(GZAxis)
			MOVEABS(POSY(0)) AXIS(GYAxis)
			WAIT UNTIL IDLE(GYAxis) 
			MOVEABS(POSX(0)) AXIS(GXAxis)
			WAIT UNTIL IDLE(GXAxis)
			
			DELAY(200)
			
			'Motion 2
			MOVEABS(POSX(4)) AXIS(GXAxis)
			WAIT UNTIL IDLE(GXAxis) 
			MOVEABS(POSX(2)) AXIS(GXAxis)
			WAIT UNTIL IDLE(GXAxis) 
			MOVEABS(POSY(4)) AXIS(GYAxis)
			WAIT UNTIL IDLE(GYAxis)
			MOVEABS(POSZ(4)) AXIS(GZAxis)
			WAIT UNTIL IDLE(GZAxis) 
			MOVEABS(POSZ(2)) AXIS(GZAxis)
			WAIT UNTIL IDLE(GZAxis)
			MOVEABS(POSY(2)) AXIS(GYAxis)
			WAIT UNTIL IDLE(GYAxis) 
			MOVEABS(POSX(1)) AXIS(GXAxis)
			WAIT UNTIL IDLE(GXAxis)
			
			
			DELAY(200)
			
			
			'Motion 3
			MOVEABS(POSX(3)) AXIS(GXAxis)
			WAIT UNTIL IDLE(GXAxis) 
			MOVEABS(POSX(3)) AXIS(GXAxis)
			WAIT UNTIL IDLE(GXAxis) 
			MOVEABS(POSY(3)) AXIS(GYAxis)
			WAIT UNTIL IDLE(GYAxis)
			MOVEABS(POSZ(3)) AXIS(GZAxis)
			WAIT UNTIL IDLE(GZAxis) 
			MOVEABS(POSZ(1)) AXIS(GZAxis)
			WAIT UNTIL IDLE(GZAxis)
			MOVEABS(POSY(1)) AXIS(GYAxis)
			WAIT UNTIL IDLE(GYAxis) 
			MOVEABS(POSX(2)) AXIS(GXAxis)
			WAIT UNTIL IDLE(GXAxis)
			
			DELAY(200)
			
			
			'Motion 4
			MOVEABS(POSX(5)) AXIS(GXAxis)
			WAIT UNTIL IDLE(GXAxis) 
			MOVEABS(POSX(4)) AXIS(GXAxis)
			WAIT UNTIL IDLE(GXAxis)
			MOVEABS(POSX(3)) AXIS(GXAxis)
			WAIT UNTIL IDLE(GXAxis)
			MOVEABS(POSX(2)) AXIS(GXAxis)
			WAIT UNTIL IDLE(GXAxis)
			MOVEABS(POSX(1)) AXIS(GXAxis)
			WAIT UNTIL IDLE(GXAxis)
			MOVEABS(POSX(5)) AXIS(GXAxis)
			WAIT UNTIL IDLE(GXAxis)
			MOVEABS(POSX(4)) AXIS(GXAxis)
			WAIT UNTIL IDLE(GXAxis)
			MOVEABS(POSX(3)) AXIS(GXAxis)
			WAIT UNTIL IDLE(GXAxis) 
			MOVEABS(POSY(4)) AXIS(GYAxis)
			WAIT UNTIL IDLE(GYAxis)
			MOVEABS(POSZ(4)) AXIS(GZAxis)
			WAIT UNTIL IDLE(GZAxis) 
			MOVEABS(POSZ(1)) AXIS(GZAxis)
			WAIT UNTIL IDLE(GZAxis)
			MOVEABS(POSY(1)) AXIS(GYAxis)
			WAIT UNTIL IDLE(GYAxis) 
			MOVEABS(POSX(2)) AXIS(GXAxis)
			WAIT UNTIL IDLE(GXAxis)
			
			DELAY(200)
			
			'Motion 5
			MOVEABS(POSX(4)) AXIS(GXAxis)
			WAIT UNTIL IDLE(GXAxis) 
			MOVEABS(POSY(5)) AXIS(GYAxis)
			WAIT UNTIL IDLE(GYAxis)
			MOVEABS(POSZ(5)) AXIS(GZAxis)
			WAIT UNTIL IDLE(GZAxis) 
			MOVEABS(POSZ(0)) AXIS(GZAxis)
			WAIT UNTIL IDLE(GZAxis)
			MOVEABS(POSY(0)) AXIS(GYAxis)
			WAIT UNTIL IDLE(GYAxis) 
			MOVEABS(POSX(3)) AXIS(GXAxis)
			WAIT UNTIL IDLE(GXAxis)
			MOVEABS(POSY(5)) AXIS(GYAxis)
			WAIT UNTIL IDLE(GYAxis)
			MOVEABS(POSZ(5)) AXIS(GZAxis)
			WAIT UNTIL IDLE(GZAxis) 
			MOVEABS(POSZ(0)) AXIS(GZAxis)
			WAIT UNTIL IDLE(GZAxis)
			MOVEABS(POSY(0)) AXIS(GYAxis)
			WAIT UNTIL IDLE(GYAxis) 
			MOVEABS(POSX(2)) AXIS(GXAxis)
			WAIT UNTIL IDLE(GXAxis) 
			MOVEABS(POSY(5)) AXIS(GYAxis)
			WAIT UNTIL IDLE(GYAxis)
			MOVEABS(POSZ(5)) AXIS(GZAxis)
			WAIT UNTIL IDLE(GZAxis) 
			MOVEABS(POSZ(0)) AXIS(GZAxis)
			WAIT UNTIL IDLE(GZAxis)
			MOVEABS(POSY(0)) AXIS(GYAxis)
			WAIT UNTIL IDLE(GYAxis) 
			MOVEABS(POSX(1)) AXIS(GXAxis)
			WAIT UNTIL IDLE(GXAxis) 
			MOVEABS(POSY(5)) AXIS(GYAxis)
			WAIT UNTIL IDLE(GYAxis)
			MOVEABS(POSZ(5)) AXIS(GZAxis)
			WAIT UNTIL IDLE(GZAxis) 
			MOVEABS(POSZ(0)) AXIS(GZAxis)
			WAIT UNTIL IDLE(GZAxis)
			MOVEABS(POSY(0)) AXIS(GYAxis)
			WAIT UNTIL IDLE(GYAxis) 
			MOVEABS(POSX(0)) AXIS(GXAxis)
			WAIT UNTIL IDLE(GXAxis)
			
			DELAY(200)
			
	WEND